# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soma1.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soma1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsoma1.proto\"\'\n\x0fRequisicaoSoma1\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1c\n\rRespostaSoma1\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\x35\n\x08Soma1RPC\x12)\n\x05Soma1\x12\x10.RequisicaoSoma1\x1a\x0e.RespostaSoma1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soma1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAOSOMA1']._serialized_start=15
  _globals['_REQUISICAOSOMA1']._serialized_end=54
  _globals['_RESPOSTASOMA1']._serialized_start=56
  _globals['_RESPOSTASOMA1']._serialized_end=84
  _globals['_SOMA1RPC']._serialized_start=86
  _globals['_SOMA1RPC']._serialized_end=139
# @@protoc_insertion_point(module_scope)
