# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import soma1_pb2 as soma1__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in soma1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Soma1RPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Soma1 = channel.unary_unary(
                '/Soma1RPC/Soma1',
                request_serializer=soma1__pb2.RequisicaoSoma1.SerializeToString,
                response_deserializer=soma1__pb2.RespostaSoma1.FromString,
                _registered_method=True)


class Soma1RPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Soma1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Soma1RPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Soma1': grpc.unary_unary_rpc_method_handler(
                    servicer.Soma1,
                    request_deserializer=soma1__pb2.RequisicaoSoma1.FromString,
                    response_serializer=soma1__pb2.RespostaSoma1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Soma1RPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Soma1RPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Soma1RPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Soma1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Soma1RPC/Soma1',
            soma1__pb2.RequisicaoSoma1.SerializeToString,
            soma1__pb2.RespostaSoma1.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
