# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soma2.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soma2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsoma2.proto\"\x1c\n\x0fRequisicaoSoma2\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\x1c\n\rRespostaSoma2\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\x37\n\x08Soma2RPC\x12+\n\x05Soma2\x12\x10.RequisicaoSoma2\x1a\x0e.RespostaSoma2(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soma2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAOSOMA2']._serialized_start=15
  _globals['_REQUISICAOSOMA2']._serialized_end=43
  _globals['_RESPOSTASOMA2']._serialized_start=45
  _globals['_RESPOSTASOMA2']._serialized_end=73
  _globals['_SOMA2RPC']._serialized_start=75
  _globals['_SOMA2RPC']._serialized_end=130
# @@protoc_insertion_point(module_scope)
